### ISSUE TITLE
Model conversion scripts in python

### ISSUE THREAD

**Issue by qingswu** [zuoqing1988/ZQCNN-v0.0#1]
Could you provide model conversion scripts in python instead of Matlab?

**Comment by zuoqing1988** [comment]
Thanks for your attention to ZQCNN. Till now, I am not farmiliar with the caffe blob storage format. When I convert a caffemodel, I load it in matlab and see how many blobs each layer has and what the shape it. The .zqparams files are all hand written line by line. So, if you want to train on new data, make sure the deploy layers are almost same as mine. A general converter from caffe to ZQCNN is far for me.

**Comment by qingswu** [comment]
Thanks for the reply, I'll try if I have some time and let you know.

**Comment by zhongwenkun886** [comment]
我编译最新的ZQCNN，文件ZQ_CNN_Forward_SSEUtils.cpp中有很多函数找不到定义，如 zq_cnn_avgpooling_nopadding_suredivided_32f_align256bit_kernel2x2_omp。
