### ISSUE TITLE
请问可以不使用SSE计算吗

### ISSUE THREAD

**Issue by uncleyoung** [zuoqing1988/ZQCNN-v0.0#12]
您好，请问ZQCNN默认开启SSE加速吗，是否可以仅使用标准C/C++进行计算？

**Comment by zuoqing1988** [comment]
不用SSE性能会慢很多，一个台式机没有理由不支持SSE啊

**Comment by zuoqing1988** [comment]
我可以考虑加一个宏来控制是否使用SSE，但是依赖的openblas是否需要SSE我就不确定了

**Comment by uncleyoung** [comment]
非常感谢您的答复。
是这样的，我想用在单片机上而不是PC，Neon、SSE等都不支持，所以需要尽量少的依赖。

**Comment by zuoqing1988** [comment]
@uncleyoung 我根本不知道单片机支持哪些指令啊，还有头文件也未必一样，这样我没法调试啊

**Comment by uncleyoung** [comment]
不调用任何指令集，普通CPU算力进行计算，就是说除了标准C++和其std库以外无其它依赖项。我试过了ncnn，经过简单改动后把所有外部依赖全删了。然后偶然发现您的实现可能会更快，所以来试试 : - )

**Comment by uncleyoung** [comment]
谢谢您的答复，我先关闭着个问题了。

**Comment by zuoqing1988** [comment]
不使用SSE的情况下，我的代码和ncnn，mini-caffe应该没有区别
