### ISSUE TITLE
人脸识别的对齐算法

### ISSUE THREAD

**Issue by joshua19881228** [zuoqing1988/ZQCNN-v0.0#18]
@zuoqing1988 感谢您的工作。请问基于mtcnn的5点人脸对齐部分的代码有c++实现吗？

**Comment by leiyu1980** [comment]
就是cpp的

**Comment by joshua19881228** [comment]
@leiyu1980 能给个链接么

**Comment by leiyu1980** [comment]
https://github.com/zuoqing1988/ZQCNN-v0.0/blob/master/ZQCNN/ZQ_CNN_MTCNN.h

**Comment by zuoqing1988** [comment]
如果想用全套方案（detect+crop+recognize, make database+ search），你可以打开ZQlibFaceID.sln来看看

**Comment by joshua19881228** [comment]
@zuoqing1988 好的，只看了ZQCNN.sln，已经找到了，谢谢~
