### ISSUE TITLE
编译找不到函数定义

### ISSUE THREAD

**Issue by zhongwenkun886** [zuoqing1988/ZQCNN-v0.0#2]
我编译最新的ZQCNN，文件ZQ_CNN_Forward_SSEUtils.cpp中有很多函数找不到定义，如 zq_cnn_avgpooling_nopadding_suredivided_32f_align256bit_kernel2x2_omp

**Comment by zuoqing1988** [comment]
@zhongwenkun886 我经常上传，可能有时候会忘了某个文件。现在时间是2018-08-15, 18:11，目前这个能编译，我刚在我机器上试了。
