### ISSUE TITLE
我发现MTCNN的检测不是特别稳定

### ISSUE THREAD

**Issue by leiyu1980** [zuoqing1988/ZQCNN-v0.0#22]
![mtcnn](https://user-images.githubusercontent.com/8098992/47069173-d179b180-d220-11e8-9ae3-7c7cacdcb4be.png)
我这个是循环检测两张照片，并作比对。发现 MTCNN检测出来的值不稳定。容易出现波动

**Comment by zuoqing1988** [comment]
你这出来的是什么信息？

**Comment by leiyu1980** [comment]
5点的x，y坐标。我发现是有可能是图片质量比较差造成的

**Comment by leiyu1980** [comment]
不过我以前用mtcnn 同样差质量的，性能要稳定些。不会波动这么大

**Comment by zuoqing1988** [comment]
你试试把CompileConfig里面的都设0，看看是否还会波动？

**Comment by leiyu1980** [comment]
好的

**Comment by zuoqing1988** [comment]
加我QQ 275918592

**Comment by leiyu1980** [comment]
我添加了  ZQ_CNN_USE_AVX 编译选项。我正在合并你新的代码，我测试后再看看，有没有这个问题。加你QQ了。。。

**Comment by leiyu1980** [comment]
新版本搞定了
