### ISSUE TITLE
线程不安全

### ISSUE THREAD

**Issue by zhongwenkun886** [zuoqing1988/ZQCNN-v0.0#6]
当在一个进程中同时用这个库做人脸检测（MTCNN）和人脸识别（MobilefacenetRes）时，人脸检测有问题，估计是底层类线程不安全。

**Comment by zuoqing1988** [comment]
你应该申请两套detector和recoginizer

**Comment by zuoqing1988** [comment]
看一下我这个例子SampleEvaluationOnLFWArcFaceZQCNN
https://github.com/zuoqing1988/ZQCNN-v0.0/blob/master/SamplesZQlibFaceID/SampleEvaluationOnLFWArcFaceZQCNN/SampleEvaluationOnLFWArcFaceZQCNN.cpp

**Comment by zhongwenkun886** [comment]
好的，谢谢
